apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirpstack-rest-api
spec:
  selector:
    matchLabels:
      app: chirpstack-rest-api
  template:
    metadata:
      labels:
        app: chirpstack-rest-api
    spec:
      containers:
      - name: chirpstack-rest-api
        image: chirpstack/chirpstack-rest-api:4.0.0
        command: ["/usr/bin/chirpstack-rest-api"]
        args: ["--server", "chirpstack-service:8080", "--bind", "0.0.0.0:8090", "--insecure"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: chirpstack-rest-api-service
spec:
  selector:
    app: chirpstack-rest-api
  ports:
  - port: 8090
    targetPort: 8090
